title: Security and Privacy Conferences for SGX.
description: Countdowns to top Security and Privacy conference deadlines.
author: SGX-Monash. Credit to Bogdan Kulynych

domain: "sgxsys.github.io"
baseurl: ""

twitter_username: # N/A
github_username: SGXSYS
github_repo: sgxsys.github.io
ga_id: UA-104921371-1

markdown: kramdown


theme: jekyll-theme-midnight
